# Generated by Django 4.2.7 on 2026-10-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_base_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفون'},
        ),
    ]
